---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/hh201020/PS_Spring_CloudConfigWATolls.git
          #username: uname
          #password:pass
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/hh201020/PS_Spring_CloudConfigWATollsPerf.git
              search-paths:
                - 'station*'